### ISSUE TITLE
 fatal error: eskf_lio/States.h: No such file or directory  #include <eskf_lio/States.h>

### ISSUE THREAD

**Issue by 911wb** [chengwei0427/ESKF_LIO#1]
感谢您做的工作，我在编译的时候遇到这个问题，请问是不是少了文件，该怎么解决？

**Comment by chengwei0427** [comment]
你好，感谢关注；
这个应该是states.msg消息类型没有生成，你可以多编译几次看看；

**Comment by iwander-all** [comment]
+1, 博主，相同问题，我也感觉是不是缺了eskf_lio/States.h这个文件

**Comment by chengwei0427** [comment]
这是一个自动生成的头文件；注意看cmakelists，如果没有，就多执行几次，生成出来就好了。

**Comment by iwander-all** [comment]
搞了好多次还是没有生成，楼主方不方便共享一下这个文件，多谢

**Comment by chengwei0427** [comment]
在cmakelists的58行，你可以注释掉部分指令，然后单独生成这个头文件
https://github.com/chengwei0427/ESKF_LIO/blob/0b2e78ec0065a506b2d53ec3fe18faf655eb0c8a/CMakeLists.txt#L58

**Comment by JixinGao** [comment]
> +1, 博主，相同问题，我也感觉是不是缺了eskf_lio/States.h这个文件

您好，请问解决了吗，是否有具体的解决方案，我也遇到了和您一样的问题

**Comment by iwander-all** [comment]
[Pose6D.h.md](https://github.com/chengwei0427/ESKF_LIO/files/9379668/Pose6D.h.md)
[States.h.md](https://github.com/chengwei0427/ESKF_LIO/files/9379669/States.h.md)
把这两个文件的后缀.md删掉，放到devel/include/eskf_lio中就可以了

**Comment by chengwei0427** [comment]
你好，手机上看不到图片。
如果是提示cloud-info相关，你可以参考legoliam或者liosam，修改一下cloud_info的消息编译。如果是其他问题，可以等我明天看一下。



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 14, 2022 07:49 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [chengwei0427/ESKF_LIO]  fatal error: eskf_lio/States.h: No such fileor directory  #include <eskf_lio/States.h&gt; (Issue #1)




 
感谢您做的工作，我在编译的时候遇到这个问题，请问是不是少了文件，该怎么解决？
