### ISSUE TITLE
您好，遇到了一个问题，体素滤波后点只剩下一个了，是点云处理部分的原因还是体素滤波器部分的原因？

### ISSUE THREAD

**Issue by JixinGao** [chengwei0427/ESKF_LIO#2]
首先非常感谢您的工作！
编译后运行时，发现位姿一直为0，通过cout测试，发现是体素滤波后，只剩下了一个点，然而体素滤波的参数我没动，依旧是0.5
`            cout << "feats_undistort = " << feats_undistort->points.size() << endl;

            downSizeFilterSurf.setInputCloud(feats_undistort);

            downSizeFilterSurf.filter(*feats_down);

            cout << "feats_down_size = " << feats_down->points.size() << endl;   `
我用上面这样的代码来显示，发现是下面的结果
`meas lidar = 17039

pcl-out = 17039

feats_undistort = 17039

feats_down_size = 1

rematch_num: 1

position: -nan -nan -nan total distance: -nan, extT: -nan -nan -nan, extR: 1 0 0
0 1 0
0 0 1
`
我走的是数据集-----
然后我修改点云接收部分，没用话题，直接把fastlio处理点云部分接过来，整体是一个ros节点，还是走到体素滤波器就变成了1个点云。而fastlio源码体素滤波一切正常，将4w多个点滤波到900左右。

**Comment by JixinGao** [comment]
目前已经解决了～应该是自己改动的时候不小心误删除了什么

**Comment by snowflakezzz** [comment]
请问是怎么解决的呀
