### ISSUE TITLE
Problem with run.

### ISSUE THREAD

**Issue by Gatsby23** [chengwei0427/ESKF_LIO#4]
您好，最近测试您算法在urbannav数据集上，一直报nan问题。想问下您现在有遇到吗？
![Screenshot from 2023-03-29 18-03-46](https://user-images.githubusercontent.com/18000675/228500203-ad06572f-2454-4c64-bee0-bbc94948f4dd.png)

我这里用的是Urbannav-hk-meidum数据集，FAST-LIO2运行没有问题。

**Comment by chengwei0427** [comment]
应该是特征点提取那里有问题，可以根据情况调整一下；特别需要注意时间戳那里

**Comment by Gatsby23** [comment]
> 应该是特征点提取那里有问题，可以根据情况调整一下；特别需要注意时间戳那里

我记得之前8月份的版本是可以的，这是留的bug吗😂

**Comment by Gatsby23** [comment]
> 应该是特征点提取那里有问题，可以根据情况调整一下；特别需要注意时间戳那里

问题出在IMU_Process地方：
```
Eigen::Vector3d acc_imu = Eigen::Vector3d::Zero(), angvel_avr = Eigen::Vector3d::Zero(), acc_avr = Eigen::Vector3d::Zero(), vel_imu(state_inout.vel_end),
```
这里需要给acc_imu，angvel_avr，acc_avr进行初始化，不然在gcc、g++-9的版本下可能存在nan问题，导致全体漂移。之前能跑可能是因为编译器版本较低，初始化直接为0.

**Comment by Gatsby23** [comment]
> 应该是特征点提取那里有问题，可以根据情况调整一下；特别需要注意时间戳那里

现在基本没问题了，感谢您的工作

**Comment by chengwei0427** [comment]
> > 应该是特征点提取那里有问题，可以根据情况调整一下；特别需要注意时间戳那里
> 
> 现在基本没问题了，感谢您的工作
那确定是参数初始化的问题吗？我有在Ubuntu16.04和Ubuntu18.04上运行过，并没有碰到你说的情况；
一般不同数据集，特征提取那里都要进行适配才行。

**Comment by Gatsby23** [comment]
> > > 应该是特征点提取那里有问题，可以根据情况调整一下；特别需要注意时间戳那里
> > 
> > 
> > 现在基本没问题了，感谢您的工作
> > 那确定是参数初始化的问题吗？我有在Ubuntu16.04和Ubuntu18.04上运行过，并没有碰到你说的情况；
> > 一般不同数据集，特征提取那里都要进行适配才行。

我这边测试的还是Urbannav上的示例数据报错的。我这边打印出来发现propagate后的值一直有nan。您应该没修改两个版本下的gcc，我Ubuntu18.04有把GCC升级到9.4+，所以出现了这个问题。

**Comment by chengwei0427** [comment]
那是有可能的。感谢你的反馈。
