### ISSUE TITLE
您好，请问为什么要用eigen库自己的实现替代ikfom呢？

### ISSUE THREAD

**Issue by DingFeng9313** [chengwei0427/ESKF_LIO#5]
最近我也在研究使用IKFOM，请问这个工具箱是有bug或者准度不够的的问题吗?我看到r3live也没有用ikfom而是用sophus自己实现的kalmanfilter。

**Comment by chengwei0427** [comment]
个人喜好吧；
我是因为没有细致研究IKFoM，所以就用eigen的。
不过IKFOM如果熟悉了，应该也会比较方便吧！

**Comment by DingFeng9313** [comment]
原来如此，谢谢

**Comment by DingFeng9313** [comment]
还想请教一下，有关FAST-LIO论文里的观测方程H。
观测方程是点云匹配的残差。H_x是观测方程对状态的倒数，为12列的矩阵，这里的状态到底是指误差error-state，还是指实际的状态？H_v是观测方程对观测误差的倒数，即1列的列向量。这个理解对吗?因为不管在您的实现还是在fastlio的实现里都没有看到H_v的函数。

**Comment by chengwei0427** [comment]
@DingFeng9313 Sorry for later reply.
1. 这里的状态，指误差状态；
2. H是观测对观测变量的雅克比，不一定是1列的列向量；你可以进行推导一下看看；
![image](https://github.com/chengwei0427/ESKF_LIO/assets/20199999/04ccdad6-526a-4535-a08c-54e7002fe777)

**Comment by DingFeng9313** [comment]
我理解了～谢谢！！

另外还向和您探讨一下。它这个把点的匹配残差作为观测量好吗？我怎么感觉还不如LMOptimization的匹配呢？或者说没有感觉它有哪些明显的优势。我感觉只是它这个观测量很新颖。forward propagation和backward propagation去畸变其实和LIO-SAM甚至LOAM里面的去畸变没有本质区别。您觉得呢？

**Comment by chengwei0427** [comment]
> 我理解了～谢谢！！
> 
> 另外还向和您探讨一下。它这个把点的匹配残差作为观测量好吗？我怎么感觉还不如LMOptimization的匹配呢？或者说没有感觉它有哪些明显的优势。我感觉只是它这个观测量很新颖。forward propagation和backward propagation去畸变其实和LIO-SAM甚至LOAM里面的去畸变没有本质区别。您觉得呢？

把匹配残差作为观测量，肯定是有效的；LMOptimization中也是把匹配残差构成优化问题，进行结算的，本质上都是优化问题；lio-sam使用优化方法，fastlio使用滤波方法，参考高博的话“滤波是滑动窗口为1的优化”，所以fastlio肯定是行之有效的。
