### ISSUE TITLE
gfs_test分支缺少文件

### ISSUE THREAD

**Issue by DingFeng9313** [chengwei0427/ESKF_LIO#6]
您好，我也想运行测试一下gfs_test分支，编译发现缺少文件，编译用的
laserMapping_gps.cpp以及 src/gnss/gps_data.cp，在切换分支后没有找到。请问时不需要这些文件吗？

**Comment by chengwei0427** [comment]
Hi, @DingFeng9313 
感谢关注！
应该是上传时没有修改对应的文件名称，你可以把laserMapping_gps改为laserMapping，然后删除gps相关的就行了。
不需要这些文件的，这里是我测试的时候改的，忘记删除了。
等我后面有空，我再整理一下这部分。
